[package]
name = "scrap"
version = "0.1.1"
authors = ["Nate Catelli <ncatelli@packetfire.org>"]
edition = "2018"

[dependencies]
parcel = { git = "https://github.com/ncatelli/parcel", tag = "v1.9.1" }
