name: Code Quality (lint, test)

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint source (cargo clippy)
        run: cargo clippy
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests (cargo test)
        run: cargo test
